-- begin PLANNER_SESSION
alter table PLANNER_SESSION add constraint FK_PLANNER_SESSION_ON_SPEAKER foreign key (SPEAKER) references PLANNER_SPEAKER(ID)^
create index IDX_PLANNER_SESSION_ON_SPEAKER on PLANNER_SESSION (SPEAKER)^
-- end PLANNER_SESSION
